name: ACG github actions 

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create Zip Bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive the artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle
      - name: Configure AWS Credentials
        uses: actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.aws_access_key}}
          aws-secret-access-ket: ${{secrets.aws_secret_access_key}}
          aws-region: us-east-1
      - name: Upload Artifacts
        run: |
            aws s3 cp ${{github.sha}}.zip s3://github-actions-123/${{github.sha}}zip
        
          
